# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'Kingfisher', '~> 4.0'
    pod 'Alamofire', '~> 4.7'
    pod 'ScrollableSegmentedControl', '~> 1.3.0'
    
    
  # Pods for Movies

  target 'MoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
